factsArray = [
"Expression_Body_Definition.html",
"Windows_File_System_Case_Sensitivity.html",
"Adding_A_Port_Number_To_A_SQL_Server_Connection_String.html",
"The_Basics_of_CORS_With_IIS.html",
"T-SQL_IN_Statement.html",
"A_New_Way_To_Format_Strings.html",
"Importing_and_Exporting_CSV_Data_From_SQLite3.html",
"SQL_String_Comparisons_Are_Not_Case_Sensitive.html",
"Checking_For_Empty_Strings_With_String_IsNullOrWhitespace.html",
"Null_Confusion.html",
"Common_Cause_of_an_InvalidOperationException.html",
"Order_of_Elements_In_A_Project_File.html",
"Easy_Date_Printing.html",
"The_Difference_Between_Readonly_and_Const.html",
]
